FROM nginx:stable-alpine

LABEL maintainer="Fabiano Honorato <fabianoshz@gmail.com>"

WORKDIR /var/www

COPY "docker/nginx/nginx.conf" "/etc/nginx/nginx.conf"

COPY "docker/nginx/default.conf" "/etc/nginx/templates/default.conf.template"

COPY ./ /var/www/

RUN chown -R nginx:nginx /var/www /var/cache/nginx /var/log/nginx /etc/nginx/conf.d

RUN chmod -R 755 /var/www

RUN touch /var/run/nginx.pid && chown -R nginx:nginx /var/run/nginx.pid

USER nginx

EXPOSE 80
